### ISSUE TITLE
Calendar Strip's selectedDate attribute is not updating after setState is called

### ISSUE THREAD

**Issue by Mekre-A** [IronLad85/bubble_animated_tabbar#1]
While using this package. I faced an issue when i was trying to update the selectedDate attribute after setState was called. The issue was the Widget does not seem to accept the new value I'm giving it. I have attached my code below
[Calendar Strip.txt](https://github.com/IronLad85/bubble_animated_tabbar/files/4379987/Calendar.Strip.txt)

**Comment by IronLad85** [comment]
> While using this package. I faced an issue when i was trying to update the selectedDate attribute after setState was called. The issue was the Widget does not seem to accept the new value I'm giving it. I have attached my code below
> [Calendar Strip.txt](https://github.com/IronLad85/bubble_animated_tabbar/files/4379987/Calendar.Strip.txt)

Can you open this issue in calendar strip repository?

**Comment by Mekre-A** [comment]
Hey man, how are you doing? So i tried your current update and i'm still
facing the same issues.Can you help me out?

**Comment by IronLad85** [comment]
sure, I still didn't fix that but yet. I'm gonna fix it asap

**Comment by Mekre-A** [comment]
Ohh okay, when you closed the issue of github I thought you did, in that
case i will keep on waiting.

Thanks,
Mekre
