### ISSUE TITLE
Calendar Strip's: selectedDate without startDate and endDate in constructor gives exception

### ISSUE THREAD

**Issue by tremp-m** [IronLad85/bubble_animated_tabbar#2]
![2020-04-01_18-25-58](https://user-images.githubusercontent.com/48671789/78148890-6d63a100-7446-11ea-827a-8f04d9d2c164.png)
![2020-04-01_18-28-03](https://user-images.githubusercontent.com/48671789/78149038-96843180-7446-11ea-9f9e-9b74c6c354e0.png)

date2.year etc request on null.....

**Comment by IronLad85** [comment]
Can you open this issue in calendar strip repository?
